defaults: &defaults
  sparqlendpoint: 'https://sparql-app.togogenome.org/sparql'
  fulltextsearch: 'https://togogenome.org/solr'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
