defaults: &defaults
  sparqlendpoint: 'http://dev.togogenome.org/sparql-app'
  fulltextsearch: 'http://dev.togogenome.org/solr'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
